### PR TITLE
8.0 improved port lmi

### PR DESCRIPTION
**Pull request by lmignon**
PR Based https://github.com/syleam/stock_scanner/pull/6
- [PEP8] The Odoo part of this addon …
- [FIX] use the user declared in the terminal to execute the scanner_call
- [IMP] refactor duplicated code and remove unused function

Based on this PR We'll develop a way to login/logout and restrict the visibility of 
the scenarii according to the groups assigned to the user and those associated to a scenario. Login/Logout will be optional and will be enabled/disabled by config.

### CODE REVIEW

**Comment by lmignon** [comment]
@sylvain-garancher Your module would be a good candidate for OCA/stock-logistick-warehouse. Have you thought about putting this module under OCA? This could generate a lot of interest for this excellent module and increase its visibility.
My 2 cents,
lmi

**Comment by Garamotte** [comment]
Hi lmi,
I already discussed about putting this module under OCA with Alexandre Fayolle during Odoo Experience. Unfortunately, I didn't have time to make the PR yet.

I don't know if it's better to take time to validate v8.0 port before proposing the module to OCA, or if the v8.0 validation can be done later, while integrated into an OCA repo.

**Comment by lmignon** [comment]
@sylvain-garancher great news! 
We'll use the module for one of our client in 8.0. If you need help to put it under OCA, I can help you. If you agree I can extract each branch with the history and do the PR on OCA . In all cases the decision is yours.

**Comment by lmignon** [comment]
@sylvain-garancher I've added some tests but they are not ran by travis since the repository is not structured as an addons rep (addons-syleam/stock_scanner). I've also improved the stock_scanner with a new way to manage the security (see #9 ) How can we proceed to have these 2 pending PR reviewed?

**Comment by Garamotte** [comment]
I think that the best way is to make a PR on an OCA repo, then rebase the changes into that repo.
I don't have time to do the OCA PR, could you do it ?

**Comment by lmignon** [comment]
@sylvain-garancher I can do all the technical stuff to move stock_logistic_warehouse to OCA. Since the module is yours, I let you you make an announce on the OCA mailing list. IMO, the best place for your addons is stock_logistic_warehouse. Once the announce is made, I'll do the PR. What do you think?

**Comment by laetitia-gangloff** [comment]
I think, that the script export_scenario has some issues.

Example :

```
<Step __last_update="2015-09-01 13:01:50" create_date="2015-09-01 12:59:40" create_uid="[1, 'Administrator']" display_name="Product EAN" name="Product EAN" no_back="False" reference_res_id="4e8a0604-50a9-11e5-bcf3-ecf4bb0a8fb9" step_back="True" step_start="True" step_stop="False" write_date="2015-09-01 13:01:50" write_uid="[1, 'Administrator']"/>
```

**create_uid="[1, 'Administrator']"**

In V7 the line is :

<Step name="Product code" no_back="True" reference_res_id="f9ac9ad0-39a3-11e2-ac36-74de2b37388c" step_back="True" step_start="False" step_stop="False"/>

**Pull request merged**
